In [2]:
#pip install transformers accelerate evaluate datasets peft -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.7 MB/s eta 0:00:00

In [3]:
#!pip install -U "torchao>=0.16.0"

Collecting torchao>=0.16.0
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 27.3 MB/s eta 0:00:00
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.18.0

In [1]:
import transformers
import accelerate
import peft
import torchao
import torch
import numpy as np
import evaluate

from datasets import load_dataset
from transformers import AutoImageProcessor
from transformers import AutoModelForImageClassification, TrainingArguments, Trainer
from torchvision.transforms import (
    CenterCrop,
    Compose,
    Normalize,
    RandomHorizontalFlip,
    RandomResizedCrop,
    Resize,
    ToTensor,
)

print(f"Transformers version: {transformers.__version__}")
print(f"Accelerate version: {accelerate.__version__}")
print(f"PEFT version: {peft.__version__}")

WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

Transformers version: 5.15.0
Accelerate version: 1.14.0
PEFT version: 0.20.0

In [2]:
model_checkpoint = "google/vit-base-patch16-224"

In [3]:
from huggingface_hub import notebook_login

notebook_login()

In [4]:
dataset = load_dataset("ethz/food101", split="train")

README.md:   0%|          | 0.00/16.4k [00:00<?, ?B/s]

data/train-00000-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  490MB

data/train-00000-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00001-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  464MB

data/train-00001-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00002-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  472MB

data/train-00002-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00003-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  464MB

data/train-00003-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00004-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  475MB

data/train-00004-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00005-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  470MB

data/train-00005-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00006-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  478MB

data/train-00006-of-00008.parquet: downloading bytes:           |  0.00B

data/train-00007-of-00008.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00007-of-00008.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  423MB

data/validation-00000-of-00003.parquet: downloading bytes:           |  0.00B

data/validation-00001-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  413MB

data/validation-00001-of-00003.parquet: downloading bytes:           |  0.00B

data/validation-00002-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  426MB

data/validation-00002-of-00003.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/75750 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/25250 [00:00<?, ? examples/s]

In [5]:
dataset = dataset.train_test_split(
    test_size=0.2,
    seed=42
)

train_dataset = dataset["train"]
val_dataset = dataset["test"]

print(len(train_dataset))
print(len(val_dataset))

60600
15150

In [6]:
labels = train_dataset.features["label"].names

label2id = {label: i for i, label in enumerate(labels)}
id2label = {i: label for i, label in enumerate(labels)}

print(len(labels))

101

In [7]:
image_processor = AutoImageProcessor.from_pretrained(
    model_checkpoint
)

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/69.7k [00:00<?, ?B/s]

In [8]:
normalize = Normalize(mean=image_processor.image_mean, std=image_processor.image_std)
train_transforms = Compose(
    [
        RandomResizedCrop(image_processor.size["height"]),
        RandomHorizontalFlip(),
        ToTensor(),
        normalize,
    ]
)

val_transforms = Compose(
    [
        Resize(image_processor.size["height"]),
        CenterCrop(image_processor.size["height"]),
        ToTensor(),
        normalize,
    ]
)


def preprocess_train(example_batch):
    """Apply train_transforms across a batch."""
    example_batch["pixel_values"] = [train_transforms(image.convert("RGB")) for image in example_batch["image"]]
    return example_batch


def preprocess_val(example_batch):
    """Apply val_transforms across a batch."""
    example_batch["pixel_values"] = [val_transforms(image.convert("RGB")) for image in example_batch["image"]]
    return example_batch

In [9]:
train_dataset.set_transform(preprocess_train)
val_dataset.set_transform(preprocess_val)

In [10]:
def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param:.2f}"
    )

In [11]:
model = AutoModelForImageClassification.from_pretrained(
    model_checkpoint,
    label2id=label2id,
    id2label=id2label,
    ignore_mismatched_sizes=True,  # provide this in case you're planning to fine-tune an already fine-tuned checkpoint
)

model.safetensors: reconstructing file:   0%|          |  0.00B /  346MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

[transformers] ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+--------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([101])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([101, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

In [12]:
print_trainable_parameters(model)

trainable params: 85876325 || all params: 85876325 || trainable%: 100.00

In [13]:
# Freeze the entire ViT backbone
for param in model.vit.parameters():
    param.requires_grad = False

# Classifier remains trainable
for param in model.classifier.parameters():
    param.requires_grad = True

In [14]:
trainable_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)

total_params = sum(
    p.numel() for p in model.parameters()
)

print(f"Trainable params: {trainable_params:,}")
print(f"All params: {total_params:,}")
print(f"Trainable %: {100 * trainable_params / total_params:.4f}%")

Trainable params: 77,669
All params: 85,876,325
Trainable %: 0.0904%

In [15]:
model_name = model_checkpoint.split("/")[-1]
batch_size = 32

args = TrainingArguments(
    output_dir=f"{model_name}-finetuned-lora-food101",
    remove_unused_columns=False,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-3,
    per_device_train_batch_size=batch_size,
    gradient_accumulation_steps=4,
    per_device_eval_batch_size=batch_size,
    fp16=True,
    num_train_epochs=5,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    push_to_hub=False,
    label_names=["labels"],
)

In [16]:
metric = evaluate.load("accuracy")


def compute_metrics(eval_pred):
    """Computes accuracy on a batch of predictions"""
    predictions = np.argmax(eval_pred.predictions, axis=1)
    return metric.compute(predictions=predictions, references=eval_pred.label_ids)

Downloading builder script: 0.00B [00:00, ?B/s]

In [17]:
def collate_fn(examples):
    pixel_values = torch.stack([example["pixel_values"] for example in examples])
    labels = torch.tensor([example["label"] for example in examples])
    return {"pixel_values": pixel_values, "labels": labels}

In [18]:
trainer = Trainer(
    model,
    args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    data_collator=collate_fn,
)
train_results = trainer.train()

/usr/local/lib/python3.13/dist-packages/PIL/TiffImagePlugin.py:950: UserWarning: Truncated File Read
  warnings.warn(str(msg))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/PIL/TiffImagePlugin.py:950: UserWarning: Truncated File Read
  warnings.warn(str(msg))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/PIL/TiffImagePlugin.py:950: UserWarning: Truncated File Read
  warnings.warn(str(msg))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/PIL/TiffImagePlugin.py:950: UserWarning: Truncated File Read
  warnings.warn(str(msg))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/PIL/TiffImagePlugin.py:950: UserWarning: Truncated File Read
  warnings.warn(str(msg))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['vit.layers.0.attention.q_proj.weight', 'vit.layers.0.attention.q_proj.bias', 'vit.layers.0.attention.k_proj.weight', 'vit.layers.0.attention.k_proj.bias', 'vit.layers.0.attention.v_proj.weight', 'vit.layers.0.attention.v_proj.bias', 'vit.layers.0.attention.o_proj.weight', 'vit.layers.0.attention.o_proj.bias', 'vit.layers.0.layernorm_before.weight', 'vit.layers.0.layernorm_before.bias', 'vit.layers.0.layernorm_after.weight', 'vit.layers.0.layernorm_after.bias', 'vit.layers.0.mlp.fc1.weight', 'vit.layers.0.mlp.fc1.bias', 'vit.layers.0.mlp.fc2.weight', 'vit.layers.0.mlp.fc2.bias', 'vit.layers.1.attention.q_proj.weight', 'vit.layers.1.attention.q_proj.bias', 'vit.layers.1.attention.k_proj.weight', 'vit.layers.1.attention.k_proj.bias', 'vit.layers.1.attention.v_proj.weight', 'vit.layers.1.attention.v_proj.bias', 'vit.layers.1.attention.o_proj.weight', 'vit.layers.1.attention.o_proj.bias', 'vit.layers.1.layernorm_before.weight', 'vit.layers.1.layernorm_before.bias', 'vit.layers.1.layernorm_after.weight', 'vit.layers.1.layernorm_after.bias', 'vit.layers.1.mlp.fc1.weight', 'vit.layers.1.mlp.fc1.bias', 'vit.layers.1.mlp.fc2.weight', 'vit.layers.1.mlp.fc2.bias', 'vit.layers.2.attention.q_proj.weight', 'vit.layers.2.attention.q_proj.bias', 'vit.layers.2.attention.k_proj.weight', 'vit.layers.2.attention.k_proj.bias', 'vit.layers.2.attention.v_proj.weight', 'vit.layers.2.attention.v_proj.bias', 'vit.layers.2.attention.o_proj.weight', 'vit.layers.2.attention.o_proj.bias', 'vit.layers.2.layernorm_before.weight', 'vit.layers.2.layernorm_before.bias', 'vit.layers.2.layernorm_after.weight', 'vit.layers.2.layernorm_after.bias', 'vit.layers.2.mlp.fc1.weight', 'vit.layers.2.mlp.fc1.bias', 'vit.layers.2.mlp.fc2.weight', 'vit.layers.2.mlp.fc2.bias', 'vit.layers.3.attention.q_proj.weight', 'vit.layers.3.attention.q_proj.bias', 'vit.layers.3.attention.k_proj.weight', 'vit.layers.3.attention.k_proj.bias', 'vit.layers.3.attention.v_proj.weight', 'vit.layers.3.attention.v_proj.bias', 'vit.layers.3.attention.o_proj.weight', 'vit.layers.3.attention.o_proj.bias', 'vit.layers.3.layernorm_before.weight', 'vit.layers.3.layernorm_before.bias', 'vit.layers.3.layernorm_after.weight', 'vit.layers.3.layernorm_after.bias', 'vit.layers.3.mlp.fc1.weight', 'vit.layers.3.mlp.fc1.bias', 'vit.layers.3.mlp.fc2.weight', 'vit.layers.3.mlp.fc2.bias', 'vit.layers.4.attention.q_proj.weight', 'vit.layers.4.attention.q_proj.bias', 'vit.layers.4.attention.k_proj.weight', 'vit.layers.4.attention.k_proj.bias', 'vit.layers.4.attention.v_proj.weight', 'vit.layers.4.attention.v_proj.bias', 'vit.layers.4.attention.o_proj.weight', 'vit.layers.4.attention.o_proj.bias', 'vit.layers.4.layernorm_before.weight', 'vit.layers.4.layernorm_before.bias', 'vit.layers.4.layernorm_after.weight', 'vit.layers.4.layernorm_after.bias', 'vit.layers.4.mlp.fc1.weight', 'vit.layers.4.mlp.fc1.bias', 'vit.layers.4.mlp.fc2.weight', 'vit.layers.4.mlp.fc2.bias', 'vit.layers.5.attention.q_proj.weight', 'vit.layers.5.attention.q_proj.bias', 'vit.layers.5.attention.k_proj.weight', 'vit.layers.5.attention.k_proj.bias', 'vit.layers.5.attention.v_proj.weight', 'vit.layers.5.attention.v_proj.bias', 'vit.layers.5.attention.o_proj.weight', 'vit.layers.5.attention.o_proj.bias', 'vit.layers.5.layernorm_before.weight', 'vit.layers.5.layernorm_before.bias', 'vit.layers.5.layernorm_after.weight', 'vit.layers.5.layernorm_after.bias', 'vit.layers.5.mlp.fc1.weight', 'vit.layers.5.mlp.fc1.bias', 'vit.layers.5.mlp.fc2.weight', 'vit.layers.5.mlp.fc2.bias', 'vit.layers.6.attention.q_proj.weight', 'vit.layers.6.attention.q_proj.bias', 'vit.layers.6.attention.k_proj.weight', 'vit.layers.6.attention.k_proj.bias', 'vit.layers.6.attention.v_proj.weight', 'vit.layers.6.attention.v_proj.bias', 'vit.layers.6.attention.o_proj.weight', 'vit.layers.6.attention.o_proj.bias', 'vit.layers.6.layernorm_before.weight', 'vit.layers.6.layernorm_before.bias', 'vit.layers.6.layernorm_after.weight', 'vit.layers.6.layernorm_after.bias', 'vit.layers.6.mlp.fc1.weight', 'vit.layers.6.mlp.fc1.bias', 'vit.layers.6.mlp.fc2.weight', 'vit.layers.6.mlp.fc2.bias', 'vit.layers.7.attention.q_proj.weight', 'vit.layers.7.attention.q_proj.bias', 'vit.layers.7.attention.k_proj.weight', 'vit.layers.7.attention.k_proj.bias', 'vit.layers.7.attention.v_proj.weight', 'vit.layers.7.attention.v_proj.bias', 'vit.layers.7.attention.o_proj.weight', 'vit.layers.7.attention.o_proj.bias', 'vit.layers.7.layernorm_before.weight', 'vit.layers.7.layernorm_before.bias', 'vit.layers.7.layernorm_after.weight', 'vit.layers.7.layernorm_after.bias', 'vit.layers.7.mlp.fc1.weight', 'vit.layers.7.mlp.fc1.bias', 'vit.layers.7.mlp.fc2.weight', 'vit.layers.7.mlp.fc2.bias', 'vit.layers.8.attention.q_proj.weight', 'vit.layers.8.attention.q_proj.bias', 'vit.layers.8.attention.k_proj.weight', 'vit.layers.8.attention.k_proj.bias', 'vit.layers.8.attention.v_proj.weight', 'vit.layers.8.attention.v_proj.bias', 'vit.layers.8.attention.o_proj.weight', 'vit.layers.8.attention.o_proj.bias', 'vit.layers.8.layernorm_before.weight', 'vit.layers.8.layernorm_before.bias', 'vit.layers.8.layernorm_after.weight', 'vit.layers.8.layernorm_after.bias', 'vit.layers.8.mlp.fc1.weight', 'vit.layers.8.mlp.fc1.bias', 'vit.layers.8.mlp.fc2.weight', 'vit.layers.8.mlp.fc2.bias', 'vit.layers.9.attention.q_proj.weight', 'vit.layers.9.attention.q_proj.bias', 'vit.layers.9.attention.k_proj.weight', 'vit.layers.9.attention.k_proj.bias', 'vit.layers.9.attention.v_proj.weight', 'vit.layers.9.attention.v_proj.bias', 'vit.layers.9.attention.o_proj.weight', 'vit.layers.9.attention.o_proj.bias', 'vit.layers.9.layernorm_before.weight', 'vit.layers.9.layernorm_before.bias', 'vit.layers.9.layernorm_after.weight', 'vit.layers.9.layernorm_after.bias', 'vit.layers.9.mlp.fc1.weight', 'vit.layers.9.mlp.fc1.bias', 'vit.layers.9.mlp.fc2.weight', 'vit.layers.9.mlp.fc2.bias', 'vit.layers.10.attention.q_proj.weight', 'vit.layers.10.attention.q_proj.bias', 'vit.layers.10.attention.k_proj.weight', 'vit.layers.10.attention.k_proj.bias', 'vit.layers.10.attention.v_proj.weight', 'vit.layers.10.attention.v_proj.bias', 'vit.layers.10.attention.o_proj.weight', 'vit.layers.10.attention.o_proj.bias', 'vit.layers.10.layernorm_before.weight', 'vit.layers.10.layernorm_before.bias', 'vit.layers.10.layernorm_after.weight', 'vit.layers.10.layernorm_after.bias', 'vit.layers.10.mlp.fc1.weight', 'vit.layers.10.mlp.fc1.bias', 'vit.layers.10.mlp.fc2.weight', 'vit.layers.10.mlp.fc2.bias', 'vit.layers.11.attention.q_proj.weight', 'vit.layers.11.attention.q_proj.bias', 'vit.layers.11.attention.k_proj.weight', 'vit.layers.11.attention.k_proj.bias', 'vit.layers.11.attention.v_proj.weight', 'vit.layers.11.attention.v_proj.bias', 'vit.layers.11.attention.o_proj.weight', 'vit.layers.11.attention.o_proj.bias', 'vit.layers.11.layernorm_before.weight', 'vit.layers.11.layernorm_before.bias', 'vit.layers.11.layernorm_after.weight', 'vit.layers.11.layernorm_after.bias', 'vit.layers.11.mlp.fc1.weight', 'vit.layers.11.mlp.fc1.bias', 'vit.layers.11.mlp.fc2.weight', 'vit.layers.11.mlp.fc2.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['vit.encoder.layer.0.attention.attention.key.bias', 'vit.encoder.layer.0.attention.attention.key.weight', 'vit.encoder.layer.0.attention.attention.query.bias', 'vit.encoder.layer.0.attention.attention.query.weight', 'vit.encoder.layer.0.attention.attention.value.bias', 'vit.encoder.layer.0.attention.attention.value.weight', 'vit.encoder.layer.0.attention.output.dense.bias', 'vit.encoder.layer.0.attention.output.dense.weight', 'vit.encoder.layer.0.intermediate.dense.bias', 'vit.encoder.layer.0.intermediate.dense.weight', 'vit.encoder.layer.0.layernorm_after.bias', 'vit.encoder.layer.0.layernorm_after.weight', 'vit.encoder.layer.0.layernorm_before.bias', 'vit.encoder.layer.0.layernorm_before.weight', 'vit.encoder.layer.0.output.dense.bias', 'vit.encoder.layer.0.output.dense.weight', 'vit.encoder.layer.1.attention.attention.key.bias', 'vit.encoder.layer.1.attention.attention.key.weight', 'vit.encoder.layer.1.attention.attention.query.bias', 'vit.encoder.layer.1.attention.attention.query.weight', 'vit.encoder.layer.1.attention.attention.value.bias', 'vit.encoder.layer.1.attention.attention.value.weight', 'vit.encoder.layer.1.attention.output.dense.bias', 'vit.encoder.layer.1.attention.output.dense.weight', 'vit.encoder.layer.1.intermediate.dense.bias', 'vit.encoder.layer.1.intermediate.dense.weight', 'vit.encoder.layer.1.layernorm_after.bias', 'vit.encoder.layer.1.layernorm_after.weight', 'vit.encoder.layer.1.layernorm_before.bias', 'vit.encoder.layer.1.layernorm_before.weight', 'vit.encoder.layer.1.output.dense.bias', 'vit.encoder.layer.1.output.dense.weight', 'vit.encoder.layer.10.attention.attention.key.bias', 'vit.encoder.layer.10.attention.attention.key.weight', 'vit.encoder.layer.10.attention.attention.query.bias', 'vit.encoder.layer.10.attention.attention.query.weight', 'vit.encoder.layer.10.attention.attention.value.bias', 'vit.encoder.layer.10.attention.attention.value.weight', 'vit.encoder.layer.10.attention.output.dense.bias', 'vit.encoder.layer.10.attention.output.dense.weight', 'vit.encoder.layer.10.intermediate.dense.bias', 'vit.encoder.layer.10.intermediate.dense.weight', 'vit.encoder.layer.10.layernorm_after.bias', 'vit.encoder.layer.10.layernorm_after.weight', 'vit.encoder.layer.10.layernorm_before.bias', 'vit.encoder.layer.10.layernorm_before.weight', 'vit.encoder.layer.10.output.dense.bias', 'vit.encoder.layer.10.output.dense.weight', 'vit.encoder.layer.11.attention.attention.key.bias', 'vit.encoder.layer.11.attention.attention.key.weight', 'vit.encoder.layer.11.attention.attention.query.bias', 'vit.encoder.layer.11.attention.attention.query.weight', 'vit.encoder.layer.11.attention.attention.value.bias', 'vit.encoder.layer.11.attention.attention.value.weight', 'vit.encoder.layer.11.attention.output.dense.bias', 'vit.encoder.layer.11.attention.output.dense.weight', 'vit.encoder.layer.11.intermediate.dense.bias', 'vit.encoder.layer.11.intermediate.dense.weight', 'vit.encoder.layer.11.layernorm_after.bias', 'vit.encoder.layer.11.layernorm_after.weight', 'vit.encoder.layer.11.layernorm_before.bias', 'vit.encoder.layer.11.layernorm_before.weight', 'vit.encoder.layer.11.output.dense.bias', 'vit.encoder.layer.11.output.dense.weight', 'vit.encoder.layer.2.attention.attention.key.bias', 'vit.encoder.layer.2.attention.attention.key.weight', 'vit.encoder.layer.2.attention.attention.query.bias', 'vit.encoder.layer.2.attention.attention.query.weight', 'vit.encoder.layer.2.attention.attention.value.bias', 'vit.encoder.layer.2.attention.attention.value.weight', 'vit.encoder.layer.2.attention.output.dense.bias', 'vit.encoder.layer.2.attention.output.dense.weight', 'vit.encoder.layer.2.intermediate.dense.bias', 'vit.encoder.layer.2.intermediate.dense.weight', 'vit.encoder.layer.2.layernorm_after.bias', 'vit.encoder.layer.2.layernorm_after.weight', 'vit.encoder.layer.2.layernorm_before.bias', 'vit.encoder.layer.2.layernorm_before.weight', 'vit.encoder.layer.2.output.dense.bias', 'vit.encoder.layer.2.output.dense.weight', 'vit.encoder.layer.3.attention.attention.key.bias', 'vit.encoder.layer.3.attention.attention.key.weight', 'vit.encoder.layer.3.attention.attention.query.bias', 'vit.encoder.layer.3.attention.attention.query.weight', 'vit.encoder.layer.3.attention.attention.value.bias', 'vit.encoder.layer.3.attention.attention.value.weight', 'vit.encoder.layer.3.attention.output.dense.bias', 'vit.encoder.layer.3.attention.output.dense.weight', 'vit.encoder.layer.3.intermediate.dense.bias', 'vit.encoder.layer.3.intermediate.dense.weight', 'vit.encoder.layer.3.layernorm_after.bias', 'vit.encoder.layer.3.layernorm_after.weight', 'vit.encoder.layer.3.layernorm_before.bias', 'vit.encoder.layer.3.layernorm_before.weight', 'vit.encoder.layer.3.output.dense.bias', 'vit.encoder.layer.3.output.dense.weight', 'vit.encoder.layer.4.attention.attention.key.bias', 'vit.encoder.layer.4.attention.attention.key.weight', 'vit.encoder.layer.4.attention.attention.query.bias', 'vit.encoder.layer.4.attention.attention.query.weight', 'vit.encoder.layer.4.attention.attention.value.bias', 'vit.encoder.layer.4.attention.attention.value.weight', 'vit.encoder.layer.4.attention.output.dense.bias', 'vit.encoder.layer.4.attention.output.dense.weight', 'vit.encoder.layer.4.intermediate.dense.bias', 'vit.encoder.layer.4.intermediate.dense.weight', 'vit.encoder.layer.4.layernorm_after.bias', 'vit.encoder.layer.4.layernorm_after.weight', 'vit.encoder.layer.4.layernorm_before.bias', 'vit.encoder.layer.4.layernorm_before.weight', 'vit.encoder.layer.4.output.dense.bias', 'vit.encoder.layer.4.output.dense.weight', 'vit.encoder.layer.5.attention.attention.key.bias', 'vit.encoder.layer.5.attention.attention.key.weight', 'vit.encoder.layer.5.attention.attention.query.bias', 'vit.encoder.layer.5.attention.attention.query.weight', 'vit.encoder.layer.5.attention.attention.value.bias', 'vit.encoder.layer.5.attention.attention.value.weight', 'vit.encoder.layer.5.attention.output.dense.bias', 'vit.encoder.layer.5.attention.output.dense.weight', 'vit.encoder.layer.5.intermediate.dense.bias', 'vit.encoder.layer.5.intermediate.dense.weight', 'vit.encoder.layer.5.layernorm_after.bias', 'vit.encoder.layer.5.layernorm_after.weight', 'vit.encoder.layer.5.layernorm_before.bias', 'vit.encoder.layer.5.layernorm_before.weight', 'vit.encoder.layer.5.output.dense.bias', 'vit.encoder.layer.5.output.dense.weight', 'vit.encoder.layer.6.attention.attention.key.bias', 'vit.encoder.layer.6.attention.attention.key.weight', 'vit.encoder.layer.6.attention.attention.query.bias', 'vit.encoder.layer.6.attention.attention.query.weight', 'vit.encoder.layer.6.attention.attention.value.bias', 'vit.encoder.layer.6.attention.attention.value.weight', 'vit.encoder.layer.6.attention.output.dense.bias', 'vit.encoder.layer.6.attention.output.dense.weight', 'vit.encoder.layer.6.intermediate.dense.bias', 'vit.encoder.layer.6.intermediate.dense.weight', 'vit.encoder.layer.6.layernorm_after.bias', 'vit.encoder.layer.6.layernorm_after.weight', 'vit.encoder.layer.6.layernorm_before.bias', 'vit.encoder.layer.6.layernorm_before.weight', 'vit.encoder.layer.6.output.dense.bias', 'vit.encoder.layer.6.output.dense.weight', 'vit.encoder.layer.7.attention.attention.key.bias', 'vit.encoder.layer.7.attention.attention.key.weight', 'vit.encoder.layer.7.attention.attention.query.bias', 'vit.encoder.layer.7.attention.attention.query.weight', 'vit.encoder.layer.7.attention.attention.value.bias', 'vit.encoder.layer.7.attention.attention.value.weight', 'vit.encoder.layer.7.attention.output.dense.bias', 'vit.encoder.layer.7.attention.output.dense.weight', 'vit.encoder.layer.7.intermediate.dense.bias', 'vit.encoder.layer.7.intermediate.dense.weight', 'vit.encoder.layer.7.layernorm_after.bias', 'vit.encoder.layer.7.layernorm_after.weight', 'vit.encoder.layer.7.layernorm_before.bias', 'vit.encoder.layer.7.layernorm_before.weight', 'vit.encoder.layer.7.output.dense.bias', 'vit.encoder.layer.7.output.dense.weight', 'vit.encoder.layer.8.attention.attention.key.bias', 'vit.encoder.layer.8.attention.attention.key.weight', 'vit.encoder.layer.8.attention.attention.query.bias', 'vit.encoder.layer.8.attention.attention.query.weight', 'vit.encoder.layer.8.attention.attention.value.bias', 'vit.encoder.layer.8.attention.attention.value.weight', 'vit.encoder.layer.8.attention.output.dense.bias', 'vit.encoder.layer.8.attention.output.dense.weight', 'vit.encoder.layer.8.intermediate.dense.bias', 'vit.encoder.layer.8.intermediate.dense.weight', 'vit.encoder.layer.8.layernorm_after.bias', 'vit.encoder.layer.8.layernorm_after.weight', 'vit.encoder.layer.8.layernorm_before.bias', 'vit.encoder.layer.8.layernorm_before.weight', 'vit.encoder.layer.8.output.dense.bias', 'vit.encoder.layer.8.output.dense.weight', 'vit.encoder.layer.9.attention.attention.key.bias', 'vit.encoder.layer.9.attention.attention.key.weight', 'vit.encoder.layer.9.attention.attention.query.bias', 'vit.encoder.layer.9.attention.attention.query.weight', 'vit.encoder.layer.9.attention.attention.value.bias', 'vit.encoder.layer.9.attention.attention.value.weight', 'vit.encoder.layer.9.attention.output.dense.bias', 'vit.encoder.layer.9.attention.output.dense.weight', 'vit.encoder.layer.9.intermediate.dense.bias', 'vit.encoder.layer.9.intermediate.dense.weight', 'vit.encoder.layer.9.layernorm_after.bias', 'vit.encoder.layer.9.layernorm_after.weight', 'vit.encoder.layer.9.layernorm_before.bias', 'vit.encoder.layer.9.layernorm_before.weight', 'vit.encoder.layer.9.output.dense.bias', 'vit.encoder.layer.9.output.dense.weight'].

In [19]:
trainer.evaluate(val_dataset)

{'eval_loss': 0.6978915333747864, 'eval_accuracy': 0.8181518151815181}

In [20]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [21]:
trainer.save_model(
    "/content/drive/MyDrive/vit-food101/models/linear_probe"
)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [22]:
import json
import os

results = {
    "method": "linear_probe",
    "model": model_checkpoint,
    "best_accuracy": trainer.evaluate()["eval_accuracy"],
    "eval_loss": trainer.evaluate()["eval_loss"],
    "train_runtime_sec": train_results.metrics["train_runtime"],
    "trainable_params": 77669,
    "total_params": 85876325,
    "trainable_pct": 0.0904,
    "epochs": 5,
    "learning_rate": 1e-3,
    "batch_size": 32,
    "gradient_accumulation_steps": 4,
    "gpu": "NVIDIA T4",
    "seed": 42,
}

In [23]:
save_dir = "/content/drive/MyDrive/vit-food101/results"
os.makedirs(save_dir, exist_ok=True)

with open(f"{save_dir}/linear_probe_metrics.json", "w") as f:
    json.dump(results, f, indent=2)

In [24]:
import pandas as pd

history = pd.DataFrame(trainer.state.log_history)

history.to_csv(
    f"{save_dir}/linear_probe_history.csv",
    index=False
)